### ISSUE TITLE
PNG export option

### ISSUE THREAD

**Issue by lhstrh** [kieler/klighd-vscode#117]
We've heard from users of the Lingua Franca VS Code extension that they miss the ability to export PNGs (currently, only SVG export is available). Is this something you might consider adding?

**Comment by NiklasRentzCAU** [comment]
No, we have not yet considered adding native PNG export yet and do not plan on adding it natively in the KLighD-VS Code extension.
Contrary to using KLighD with Piccolo2D, KLighD in the VS Code extension does not connect to any native rendering library, but uses SVGs in their core, which will eventually be rendered by the Chromium browser inside VS Code. A native implementation may therefore need an integrated SVG renderer in the extension.

Currently the suggested way to export a PNG is to either take a screenshot of the diagram directly or to use the usual SVG export and rasterize that with an external tool such as Inkscape to PNG.
