### ISSUE TITLE
Need to run `yarn build` before `yarn watch`

### ISSUE THREAD

**Issue by kasbah** [kieler/klighd-vscode#119]
I ran into issues running `yarn watch` after `yarn` as instructed in the readme. I needed to run `yarn build` once otherwise I got errors because it can't find the klighd-core module:

```
Cannot find module '@kieler/klighd-core'
```

**Comment by NiklasRentzCAU** [comment]
Thanks, never noticed this before because this only affects clean repositories, as the `watch` task runs over all packages in parallel, therefore missing the internal dependencies. Added your suggested step in the readme.
