### ISSUE TITLE
Should we add the need for the Overpass font to the documentation?

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#148]

**Comment by NiklasRentzCAU** [comment]
What about this, is it not enough? https://github.com/kieler/klighd-vscode/wiki/Exporting-Diagrams-as-SVG-and-PDF

The Overpass Font is only needed to be installed when viewing it with a viewer that does not support embedded fonts, such as Inkscape or some basic SVG viewers. For viewing in Chrome(ium), no Font install is needed.
