### ISSUE TITLE
Gradient in SVG support broken

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#38]
It seems to be the case that the gradient in the SCCharts visualization is not correctly exported. At least, if the file is opened in inkscape this is not the case.

To check:

What happens if SCChart is exported to svg in KIELER and VSCode

Do they look the same?
How about opening them in inkscape
How about exporting them to pdf via inkscape cli?

**Comment by Eddykasp** [comment]
To expand on this issue: the problem doesn't happen upon opening the svg in Inkscape (or other svg viewers), but only once certain operations in inkscape are performed. For example resizing the image triggers it. This may be a problem in Inkscape.

**Comment by Eddykasp** [comment]
[Issue for Inkscape](https://gitlab.com/inkscape/inbox/-/issues/6845)

**Comment by Eddykasp** [comment]
The issue is already known [Issue 2956](https://gitlab.com/inkscape/inkscape/-/issues/2956)

A potential temporary fix could be to define the gradients differently:

> If you replace gradientTransform="rotate(90)" with x1="0" x2="0" y1="0" y2="1" it appears to work fine

maybe @NiklasRentzCAU has some input on whether changing this in the rendering is worth the effort?

**Comment by NiklasRentzCAU** [comment]
Thanks for that hint, #69 will work around the issue in Inkscape and use the gradient coordinates instead of the gradient angle definitions.
