### ISSUE TITLE
Code association does not work correctly

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#80]
Reported for klighd-vscode 0.2.1

Default option should be:
- diagram should select text
- text should not select diagram

Everything else is confusing as default.

This may already be fixed. However, we need to check this.

**Comment by NiklasRentzCAU** [comment]
Already fixed in commit [b2d8dea3f3dfbe20ff3dba1d835ebb024a949711](https://github.com/kieler/klighd-vscode/commit/b2d8dea3f3dfbe20ff3dba1d835ebb024a949711).
Will be included in the next release.
