### ISSUE TITLE
Calculate absolute coordinates on server and store directly in sknodes

### ISSUE THREAD

**Issue by Eddykasp** [kieler/klighd-vscode#82]
Several features, such as incremental diagram generation, to an extent the depth map and the future proxy-view require the absolute coordinates of nodes and compute them independently. This redundancy should be extracted and centralized, possibly to the language server.

**Comment by NiklasRentzCAU** [comment]
As we tried to off-load several parts of the diagram generation to the client to reduce the necessary amount of data sent during communication (which still is a bigger part of the generation time) I think the centralization could also be on the client side. What about the depth map, can't that be used as a central point for that? Maybe that class just needs a rename to better reflect what it does.

**Comment by Eddykasp** [comment]
Yes I think the depth map would be a good place to put this stuff, although for the incremental diagram generation this would be too late. Currently there is no implementation of the piece requesting strategy which actually uses precise coordinates though. It's just something to keep in mind.

**Comment by Eddykasp** [comment]
If we do decide to centralize this responsibility onto the depth map we also need to consider this [issue](https://github.com/kieler/klighd-vscode/issues/77).
