### ISSUE TITLE
Nodes have wrong detail level (Smart Zoom)

### ISSUE THREAD

**Issue by fight4day** [kieler/klighd-vscode#87]
Under certain conditions, nodes appear to have a wrong detail level.

Steps to reproduce:
- on main branch, latest commit
- if not off already, turn 'Resize To Fit' off in the sidebar
- open a diagram, e.g. running example `motor.sctx`
- resize the new panel the diagram was opened in until the panel is as small as possible regarding the width (now some nodes should be off-screen)
- turn 'Resize To Fit' on in the sidebar
- again resize the panel until approximately back to standard size
- when navigating the diagram, some nodes appear as though the user is zoomed out a lot (they have that magnifying glass symbol)
- turning 'Smart Zoom' off fixes this bug

Screenshot:
![smart-zoom-bug](https://user-images.githubusercontent.com/61043946/170953938-4615cf5c-0e66-4254-908a-78a9a74edce2.png)

**Comment by NiklasRentzCAU** [comment]
Cannot reproduce this issue anymore, it seems to have fixed itself with some recent changes.
