### ISSUE TITLE
Incremental Diagram Generation does not work

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#88]
MessageConnection sends requestDiagramPiece action does not get an answer.

**Comment by NiklasRentzCAU** [comment]
This issue does not happen when starting the LS from socket (from dev Eclipse or from build LS jar), but does occur when starting the extension normally (using the exact same jar), therefore this is not easily debuggable. Do you write anything off into the output stream that may break things here @Eddykasp ?
