### ISSUE TITLE
Not selectable text should still be able to execute its actions

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#90]
See https://github.com/kieler/vscode/issues/32

**Comment by soerendomroes** [comment]
In piccolo not selectable elements are still used evaluated for their actions. E.g. if one clicks on an KStyledText with actions that is not selectable the pickedNode in processEvent in KlighdActionEventHandler is still the KSytledText. In VS Code this is not the case but the text cannot be clicked since it is not selectable.

**Comment by soerendomroes** [comment]
@NiklasRentzCAU want else do we need to know to implement it the same way as in piccolo?

**Comment by NiklasRentzCAU** [comment]
The intended behavior of KLighD action execution as it is implemented with Piccolo is not possible to implement with the event handler of Sprotty and needs dedicated event handlers on the SVG elements representing KRenderings with attached KActions.

The wanted behavior would check the elements from the topmost visible SVG element for attached actions, and continue to forward the event handling to the first element seen from the front with an action, stopping there and executing if triggers match. As SVG elements drawn directly behind other SVG elements do not need to be their parent element (see for example the +/- text for region collapsing/expanding in front of but not contained in the triangle behind) a single event handler bubbling its way through its parent hierarchy does not suffice to get the same behavior.
Using Sprotty we currently define a single event handler on the top level SVG (the currentTarget in events) that triggers and has that top level SVG visible, as well as the deepest SVG element that was clicked on (the target in events) with no reference to the SVG element stack as it is drawn on screen, only the parent hierarchy, which is not the same.

A possible solution could add event listeners to every child SVG element and forward clicks to a central action handler, making sure to only execute an action on the top most element with an attached action (if applicable).

A simpler workaround could fix the current action handling to traverse through their parents to find actions and execute them (as is done currently) and ignore the fact that overlayed sibling elements cannot bubble the events, requiring a simple change in the semantics to make the +/- buttons work again.

**Comment by soerendomroes** [comment]
I don't understand fully the implications of the two alternatives but it seems to be that alternative one would be the solution we would benefit from in the long run.
